# Generated by Django 5.1.7 on 2025-03-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('developer', 'Developer'), ('manager', 'Manager'), ('tester', 'Tester'), ('guest', 'Guest')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('task_type', models.CharField(choices=[('bug', 'Bug Fix'), ('feature', 'Feature Development'), ('improvement', 'Improvement'), ('documentation', 'Documentation'), ('testing', 'Testing'), ('deployment', 'Deployment'), ('research', 'Research')], default='feature', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_users', models.ManyToManyField(related_name='tasks', to='tasks.usermodel')),
            ],
        ),
    ]
